tag-format: '%s/php:%s'

dirs:
  - alpine
  - debian

tags:
  ./alpine/3.12/7.3/Dockerfile:
    - latest
    - 7.3

  ./alpine/3.12/7.4/Dockerfile:
    - 7.4

  ./alpine/3.12/8.0/Dockerfile:
    - 8.0

  ./debian/bullseye/8.0/Dockerfile:
    - 8.0-debian

  ./debian/bullseye/7.4/Dockerfile:
    - 7.4-debian

  ./debian/bullseye/7.3/Dockerfile:
    - 7.3-debian

